name: Test DevOps Installer

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure Homebrew is installed
        run: |
          if ! command -v brew &>/dev/null; then
            echo "Installing Homebrew..."
            NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          else
            echo "✅ Homebrew already installed"
          fi

      - name: Install gum
        run: brew install charmbracelet/tap/gum

      - name: Install pipx
        run: |
          brew install pipx
          pipx ensurepath

      - name: Run DevOps Installer
        run: |
          chmod +x setup-devops-gui.sh
          bash ./setup-devops-gui.sh <<< $'\n'  # Пропустить интерактив при CI

      - name: Verify installed tools
        run: |
          TOOLS=(
            git zsh fzf jq bat tree docker docker-compose
            kubectl helm k9s minikube terraform
            aws gcloud az gh glab pipx ansible
            visual-studio-code iterm2 act tailscale ngrok
            direnv zoxide httpie cheat btop
          )

          echo "🔍 Проверка установленных инструментов..."
          for tool in "${TOOLS[@]}"; do
            if ! command -v "$tool" &>/dev/null; then
              echo "❌ $tool НЕ УСТАНОВЛЕН!"
              exit 1
            else
              echo "✅ $tool установлен"
            fi
          done

      - name: Success
        run: echo "🎉 Все DevOps-инструменты успешно установлены и проверены!"
