name: Test DevOps CLI Installer

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Homebrew, pipx and gum
        run: |
          if ! command -v brew &>/dev/null; then
            NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi
          brew install pipx
          pipx ensurepath
          brew install charmbracelet/tap/gum

      - name: Configure shell environment
        run: |
          eval "$(/opt/homebrew/bin/brew shellenv)" >> ~/.bash_profile
          eval "$(/opt/homebrew/bin/brew shellenv)"
          export PATH="$HOME/.local/bin:$PATH"

      - name: Run setup-devops-cli.sh with --all
        run: |
          chmod +x setup-devops-cli.sh
          ./setup-devops-cli.sh --all

      - name: Verify installed CLI tools
        shell: bash
        run: |
          export PATH="$HOME/.local/bin:$PATH"

          TOOLS=(
            git zsh fzf jq bat tree
            kubectl helm k9s terraform
            aws az gh glab pipx ansible
            act direnv zoxide httpie cheat btop
          )

          echo "🔍 Проверка установленных CLI-инструментов..."
          FAIL=0
          for tool in "${TOOLS[@]}"; do
            if ! command -v "$tool" &>/dev/null; then
              echo "❌ $tool НЕ УСТАНОВЛЕН!"
              FAIL=1
            else
              echo "✅ $tool установлен"
            fi
          done

          if [[ "$FAIL" -ne 0 ]]; then
            echo "❌ Некоторые CLI-инструменты не были установлены"
            exit 1
          fi

      - name: Success
        if: success()
        run: echo "🎉 Все CLI-инструменты DevOps успешно установлены и проверены!"
